### ISSUE TITLE
Add NeurIPS-2023 Video Generation Paper

### ISSUE THREAD

**Issue by wangxiang1230** [diff-usion/Awesome-Diffusion-Models#106]
Hi, thanks for providing such a meaningful survey project. Could you please help to add the following paper:

Paper name: VideoComposer: Compositional Video Synthesis with Motion Controllability (NeurIPS-2023)
Paper link: https://arxiv.org/abs/2306.02018
Project link: https://videocomposer.github.io/
Code link: https://github.com/damo-vilab/videocomposer
Related area: Video Generation, Controllable Video Generation

Thank you!

**Comment by diff-usion** [comment]
Heello @wangxiang1230 ,

it is now added. Thank you for your outstanding work!
