### ISSUE TITLE
An arxiv paper is accepted by NeurIPS 2023

### ISSUE THREAD

**Issue by ThomasMrY** [diff-usion/Awesome-Diffusion-Models#108]
Thank you for constructing such a great repo! We have a update for paper listed: Could you do some modification to the paper "DisDiff: Unsupervised Disentanglement of Diffusion Probabilistic Models" by Tao Yang. It has been accepted by NeurIPS 2023.

**Comment by diff-usion** [comment]
It has been now added. Thank you @ThomasMrY !
