### ISSUE TITLE
Add ICCV 2023 video editing paper: StableVideo

### ISSUE THREAD

**Issue by rese1f** [diff-usion/Awesome-Diffusion-Models#92]
Hi! Could you please include our work StableVideo at ICCV 2023? Thank you so much!

StableVideo: Text-driven Consistency-aware Diffusion Video Editing
Wenhao Chai, Xun Guo, Gaoang Wang, Yan Lu
ICCV 2023
https://arxiv.org/abs/2308.09592

**Comment by diff-usion** [comment]
The paper is now added. Thank you.
